# Generated by Django 4.1.4 on 2023-07-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listings_other_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='other_photos',
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listings'),
        ),
    ]
